static const unsigned long int node_count = 2023;
static const unsigned long int node_child_index_count = 2022;
static const unsigned long int node_mesh_index_count = 2057;
static const unsigned long int raytraced_surface_node_count = 3;
extern const unsigned long int raytraced_surface_nodes[raytraced_surface_node_count * 2];
static const unsigned long int revision_logo_node_index = 20;
static const unsigned long int cave_node_index = 41;
static const unsigned long int village_node_index = 102;
static const unsigned long int windmill_vanes_node_index = 312;
static const unsigned long int blossom_node_index = 313;
static const unsigned long int crystals_node_index = 473;
static const unsigned long int rocket_node_index = 498;
static const unsigned long int skyscraper_node_count = 4;
extern const unsigned long int skyscraper_nodes[skyscraper_node_count];
static const unsigned long int chunked_node_count = 11;
extern const unsigned long int chunked_nodes[chunked_node_count];
extern const unsigned long int node_child_indices[node_child_index_count];
extern const unsigned long int node_mesh_indices[node_mesh_index_count];
extern const unsigned long int node_child_offsets[node_count + 1];
extern const unsigned long int node_mesh_offsets[node_count + 1];
extern const float node_transformations[node_count*16];
